# Generated by Django 4.0.3 on 2022-05-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_remove_user_passward_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
